### ISSUE TITLE
Pod Not Working

### ISSUE THREAD

**Issue by tapannathvani** [AgoraIO-Community/iOS-UIKit#1]
When i tried to install pod file pod ‘AgoraUIKit', i am getting below error and there is no any documentation at agora site like how to implement iOS with pod file. I have done demo using Framework only but now need to do with Pod file but its not working. 

Analyzing dependencies
[!] No podspec exists at path `/Users/XXXX/.cocoapods/repos/trunk/Specs/1/d/9/AgoraRtcEngine_iOS/3.1.2.60/AgoraRtcEngine_iOS.podspec.json`.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform `iOS` with version `12.0` on target `AgoraDemo` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by zontan** [comment]
It looks like you're using an out of date trunk. Run `pod repo update` to get the latest version of all the repositories.

**Comment by tapannathvani** [comment]
Its working. Thanks
