### ISSUE TITLE
Invalid Token Error while creating recording

### ISSUE THREAD

**Issue by tapannathvani** [AgoraIO-Community/iOS-UIKit#2]
Hello,

We are trying to create recording for one to one person.
1. We are calling an API to our server
2. Server generates token, sid, resourceid & uid and send back to front end
3. we are passing the same data to joinchannel method.

Still we are getting invalid token error

**Comment by yoreland** [comment]
duplicated on https://github.com/AgoraIO/Basic-Video-Call/issues/249
Let us discuss there..
