### ISSUE TITLE
Is it possible to receive a video call when the app is terminated, and answer this video call ?

### ISSUE THREAD

**Issue by basmaamahmoud** [AgoraIO-Community/iOS-UIKit#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxxfrazer** [comment]
Hi, what you're looking for is how to integrate CallKit in an Agora application. You can check out these links, but a lot of it needs to be set up with Apple, and is not part of the Agora UIKit frameworks.

Agora CallKit FAQ:
https://docs.agora.io/en/All/faq/call_invite_notification

Apple CallKit Docs:
https://developer.apple.com/documentation/callkit
