### ISSUE TITLE
Facing Multiple screen When Tap sharing pin view of collection

### ISSUE THREAD

**Issue by DeviOSSushant01** [AgoraIO-Community/iOS-UIKit#58]
I am implemented screenSharing features use of UIKit screenSharing working good but when we tap on screen sharing view which is show in collection of style .floating then it show multiple view of sharing in device.

![E113207E-2559-45A9-B7F9-84B7AD853DB7](https://user-images.githubusercontent.com/96534140/150640112-6f1d4f5a-54c8-4b58-b15a-40d7e645f387.jpg)

**Comment by maxxfrazer** [comment]
Hi @DeviOSSushant01 this seems to be the correct behaviour - for any applications screen sharing you can get this infinite loop behaviour.

Let me know if I'm misunderstanding the question there
