### ISSUE TITLE
Is video calling on dynamic channels at same time is avalable in flutterUIkit

### ISSUE THREAD

**Issue by alimajid124** [AgoraIO-Community/iOS-UIKit#63]
i am making an app which need to make multiple groups calls with different users by subadmins, is it possible using **agoraUIKIT**

**Comment by maxxfrazer** [comment]
Yes. Is there a particular part that doesn't seem possible with UIKit?

**Comment by maxxfrazer** [comment]
Something like this for example?
https://www.agora.io/en/blog/connecting-to-multiple-channels-with-agora-on-ios/

**Comment by alimajid124** [comment]
Yes....but i want to ask that can we implement this real time video call
with agoraUI kit...as i have to make multiple channels...so if i use
agoraUI kit...how i can make it ?

**Comment by maxxfrazer** [comment]
Sorry for the delay, I've been away.

What part of that are you having trouble with? I may not be understanding the question fully

**Comment by alimajid124** [comment]
When we intialize agora UIkit, we give tokenURL to get token from server.
So when i place my URL in thsy tokenURL field..it didn't work. Give error
of invalid token.
I think it doesn't fetch the token.
I had send code with token url in previous mail. Kindly check.

**Comment by maxxfrazer** [comment]
Is this a different issue than above?
You mentioned flutter UIKit, is the issue with this one or the flutter one?
What URL are you passing?
Any logs?

**Comment by alimajid124** [comment]
Let me share you url

**Comment by maxxfrazer** [comment]
Hi @alimajid124, is this working now? Is it for the Flutter UIKit or iOS UIKit?

**Comment by alimajid124** [comment]
No agora UIkit is now not working on updated flutter. Kindly check

**Comment by maxxfrazer** [comment]
Is this a new issue then?
If it's a problem with the flutter uikit, then you're better off opening an issue on that repo. this is the one for iOS uikit, using swift.

**Comment by alimajid124** [comment]
Please tell me when will update of agoraUIkit will release accordingly to
flutter new version, now agora video calling is not working.
I have to release app for production level. It is delaying my work

**Comment by alimajid124** [comment]
Hi Max
         I am your customer using agora UIKit and Agora RTC packages in
flutter  , as we were near to production phase of our app, these packages
stop working which delay production of our app. Flutter was updated and
agora should also synchronised their packages with that.
I request if you make any update which could effect our working kindly
update me.
I am your customer, using your product, i should know in email so we could
do proper setup.
Thanks

**Comment by maxxfrazer** [comment]
I’m not sure if you realises at this point, but I am responding via an issue opened on GitHub on the iOS UIKit.
Your problem is with the Flutter UIKit. To progress, you will need to open an issue there following the suggested format, which would include the version of our package, and in this specific case the URL being used for the token server.
Link is: https://github.com/AgoraIO-Community/Flutter-UIKit/issues

**Comment by alimajid124** [comment]
Ok,

**Comment by alimajid124** [comment]
actually I am using agoraUIKIt for flutter, when i updated the flutter
version to 3.0 , agoraUIKIt is not responding. i am unable to use it. i
have to update my app to production level, but now unable to do this

**Comment by maxxfrazer** [comment]
this is the wrong thread, please reply here giving the requested information:
https://github.com/AgoraIO-Community/VideoUIKit-Flutter
